// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;

namespace Net5.AspNet.Exam.Infrastructure.Data.Classroom.Contexts
{
    public partial class ClassroomContext
    {

        [DbFunction("CheckRoleByUserId", "Security")]
        public static string CheckRoleByUserId(string UserId, string RoleName)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }
    }
}
