// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Net5.AspNet.Exam.Infrastructure.Data.Classroom.Entities
{
    public partial class Course
    {
        public Course()
        {
            Grades = new HashSet<Grade>();
        }

        public int CourseId { get; set; }
        public string Description { get; set; }
        public string CreationUserId { get; set; }
        public DateTime CreationDate { get; set; }
        public string UpdateUserId { get; set; }
        public DateTime UpdateDate { get; set; }

        public virtual ICollection<Grade> Grades { get; set; }
    }
}