// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Net5.AspNet.Exam.Infrastructure.Data.Classroom.Entities
{
    public partial class Grade
    {
        public int GradeId { get; set; }
        public decimal Value { get; set; }
        public int StudentId { get; set; }
        public int CourseId { get; set; }
        public string CreationUserId { get; set; }
        public DateTime CreationDate { get; set; }
        public string UpdateUserId { get; set; }
        public DateTime UpdateDate { get; set; }

        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
    }
}