// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Net5.AspNet.Exam.Infrastructure.Data.Classroom.Contexts.Configurations;
using Net5.AspNet.Exam.Infrastructure.Data.Classroom.Entities;
using System;

#nullable disable

namespace Net5.AspNet.Exam.Infrastructure.Data.Classroom.Contexts
{
    public partial class ClassroomContext : DbContext
    {        
        public virtual DbSet<User> Users { get; set; }
                
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
        {            
            modelBuilder.ApplyConfiguration(new UserConfiguration());            
        }
    }
}
