// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Net5.AspNet.Exam.Infrastructure.Data.Classroom.Entities
{
    public partial class Course
    {        
        public virtual User CreationUser { get; set; }
        public virtual User UpdateUser { get; set; }     
    }
}